### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by gjhklfdsa** [larvalabs/cryptopunks#17]
**Source**: https://archive.fo/yWJv5

Please don't let this be the end of CryptoPunks!

Error Message:

> The page isn’t redirecting properly
> 
> Firefox has detected that the server is redirecting the request for this address in a way that will never complete.
> 
>     This problem can sometimes be caused by disabling or refusing to accept cookies.

Browser: [Firefox](https://www.wikipedia.org/wiki/Firefox) ([TOR](https://www.wikipedia.org/wiki/Tor_(anonymity_network)#Tor_Browser))

**Comment by megamattron** [comment]
Thanks for the heads up, should be back online now!

**Comment by gjhklfdsa** [comment]
@megamattron No problem. Whatever the issue was seems to have been fixes[1](https://archive.fo/T1Nqw).
