### ISSUE TITLE
Found variables that are declared but not used anywhere.  Major security flaw

### ISSUE THREAD

**Issue by philipjonsen** [larvalabs/cryptopunks#31]
Description
Variables that aren't defined, but accessed may throw reference errors at runtime.

NOTE: In browser applications, DeepSource recommends the use of ESModules over regular text/javascript scripts. Using variables that are injected by scripts included in an HTML file is currently not supported.

Potential ReferenceErrors may result from misspellings of variable and parameter names, or accidental implicit globals (for example, forgetting the var keyword in a for loop initializer). Any reference to an undeclared variable causes a warning, unless the variable is explicitly mentioned in a /*global ...*/ comment, or specified in the globals key in the configuration file. A common use case for these is if you intentionally use globals that are defined elsewhere (e.g. in a script sourced from [HTML).](

https://github.com/philipjonsen/cryptopunks/blob/cryptosweden/migrations/1_initial_migration.js#L1-L1

https://github.com/philipjonsen/cryptopunks/blob/cryptosweden/migrations/2_deploy_contracts.js#L3-L3
'
https://github.com/philipjonsen/cryptopunks/blob/cryptosweden/migrations/2_deploy_contracts.js#L3-L3

**Comment by megamattron** [comment]
These are in old and unused javascript deployment scripts, so closing.
