### ISSUE TITLE
Bid address not replaced

### ISSUE THREAD

**Issue by otpyrc** [larvalabs/cryptopunks#5]
I placed a bid on punk #3307 for .155 ether and it looks like the address of the bid before mine just stayed there.  Either that or they were able to trump my bid with the exact same amount.  Either way, my bid is apparently not valid, and I'm currently still missing the .155 ether.

**Comment by otpyrc** [comment]
Scratch that, upon checking again, I was able to withdraw it.  There still may be a problem though, with somebody being able to bid the same amount and have the highest bid.  Unless they added value to the fourth decimal place and it just isn't showing.  I'd be curious to know what's up.  Thanks

**Comment by pents90** [comment]
Yup, we'll check it out. The code for bidding does require that the bid be
higher before it can replace an existing bid, so maybe they are just nosing
you out by a tiny amount:
https://github.com/larvalabs/cryptopunks/blob/migration/contracts/CryptoPunksMarket.sol#L202

The bids can be viewed by inspecting the contract directly in your wallet
software.

**Comment by otpyrc** [comment]
Lightning fast response!  Kudos :)

**Comment by pents90** [comment]
And sure enough, the bid is just slightly higher than .155:

![image](https://user-images.githubusercontent.com/649612/27523473-6a0066e6-59fb-11e7-9469-484ec0781366.png)

**Comment by otpyrc** [comment]
That bastard! hahaha....  What is this, The Price is Right?

**Comment by pents90** [comment]
He's acting like... a punk!

**Comment by megamattron** [comment]
Mystery solved, but I'm also suggesting in #8 we add more info to the page to make situations like this more understandable.
